baseURL = 'https://homepage.rakkyo150.workers.dev'
languageCode = 'ja'
title = 'rakkyo150のMod・ツールまとめ'
theme = "blowfish"
enableRobotsTXT = false
# https://gohugo.io/getting-started/configuration/#capitalizelisttitles
capitalizeListTitles = false

[params]
  colorScheme = "fire"
  enableSearch = true
  enableCodeCopy = true
  smartTOC = true
  defaultSocialImage = "banner.png"

[params.author]
  name = "rakkyo150"
  image = "https://avatars.githubusercontent.com/u/86054813?s=350&v=4"
  headline = "BeatSaber関係を中心に色々開発している"
  links = [
    { x-twitter = "https://x.com/rakkyo150" },
    { github = "https://github.com/rakkyo150"}
  ]

[params.article]
showTableOfContents = true
relatedContentLimit = 10
showPagination = false
showReadingTime = false
showTaxonomies = true 
showDateUpdated = true
showWordCount = false

[params.list]
cardView = true
groupByYear = false

[taxonomies]
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]