baseURL = 'https://homepage.rakkyo150.workers.dev'
languageCode = 'ja'
title = 'rakkyo150のMod・ツールまとめ'
theme = "blowfish"
logo = "logo.png"
enableRobotsTXT = false

[params]
  colorScheme = "fire"

[params.author]
  name = "rakkyo150"
  image = "https://avatars.githubusercontent.com/u/86054813?s=350&v=4"
  headline = "BeatSaber関係を中心に色々開発している"
  links = [
    { x-twitter = "https://x.com/rakkyo150" },
    { github = "https://github.com/rakkyo150"}
  ]

[params.article]
showTableOfContents = true
relatedContentLimit = 10
showPagination = false

[params.list]
cardView = true

[taxonomies]
tag = "tags"
series = "series"