name = "homepage"
compatibility_date = "2025-10-18"
main = "./src/index.ts"

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
binding = "ASSETS"
directory = "./public"
run_worker_first = true