backend:
  name: github
  repo: rakkyo150/rakkyo150.github.io
  branch: hugo
  base_url: https://homepage.rakkyo150.workers.dev
  auth_endpoint: /auth
media_folder: static/uploads
public_folder: /uploads
collections:
  - name: '対応表'
    label: '対応表'
    folder: 'content/compatible_table'
    editor:
      preview: true
    fields:
      - { label: 'タイトル', name: 'title', widget: 'string' }
      - { label: '日付', name: 'date', format: 'YYYY-MM-DDTHH:mm:ssZ', widget: 'datetime' }
      - { label: '更新日', name: 'lastmod', format: 'YYYY-MM-DDTHH:mm:ssZ', widget: 'datetime' }
      - { label: 'タグ', name: 'tags', widget: 'list' }
      - { label: '本文', name: 'body', widget: 'markdown' }
  - name: 'BeatSaber関係'
    label: 'BeatSaber関係'
    folder: 'content/production/BeatSaber'
    editor:
      preview: true
    fields:
      - { label: 'タイトル', name: 'title', widget: 'string' }
      - { label: '日付', name: 'date', format: 'YYYY-MM-DDTHH:mm:ssZ', widget: 'datetime' }
      - { label: '更新日', name: 'lastmod', format: 'YYYY-MM-DDTHH:mm:ssZ', widget: 'datetime' }
      - { label: 'タグ', name: 'tags', widget: 'list' }
      - { label: '本文', name: 'body', widget: 'markdown' }
  - name: 'ツール'
    label: 'ツール'
    folder: 'content/production/tool'
    editor:
      preview: true
    fields:
      - { label: 'タイトル', name: 'title', widget: 'string' }
      - { label: '作成日', name: 'date', format: 'YYYY-MM-DDTHH:mm:ssZ', widget: 'datetime' }
      - { label: '更新日', name: 'lastmod', format: 'YYYY-MM-DDTHH:mm:ssZ', widget: 'datetime' }
      - { label: 'タグ', name: 'tags', widget: 'list' }
      - { label: '本文', name: 'body', widget: 'markdown' }
  - name: '記事'
    label: '記事'
    folder: 'content/article'
    slug: "{{slug}}"
    create: true
    editor:
      preview: true
    fields:
      - { label: 'タイトル', name: 'title', widget: 'string' }
      - { label: '日付', name: 'date', format: 'YYYY-MM-DDTHH:mm:ssZ', widget: 'datetime' }
      - { label: '更新日', name: 'lastmod', format: 'YYYY-MM-DDTHH:mm:ssZ', widget: 'datetime', required: false }
      - { label: '読了時間の表示', name: 'showReadingTime', widget: "boolean", default: true}
      - { label: 'シリーズ', name: 'series', widget: 'list', required: false }
      - { label: 'シリーズ番号', name: 'series_order', widget: 'number', required: false }
      - { label: 'タグ', name: 'tags', widget: 'list', required: false }
      - { label: '本文', name: 'body', widget: 'markdown' }